import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — Sentinel Trading Platform',
  description: 'Sentinel Trading Platform Terms of Service',
};

export default function TermsPage() {
  return (
    <article className="prose prose-neutral dark:prose-invert max-w-none">
      <h1>Terms of Service</h1>
      <p className="text-muted-foreground text-sm">Version 1.0.0 — Effective April 1, 2025</p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using the Sentinel Trading Platform (&quot;Platform&quot;), you agree to be
        bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to all the terms
        and conditions, you must not use the Platform.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        Sentinel is an evidence-based systematic trading platform that provides portfolio analytics,
        strategy monitoring, signal tracking, and AI-assisted trading recommendations. The Platform
        is intended for informational and analytical purposes.
      </p>

      <h2>3. Account Registration</h2>
      <p>
        You must provide accurate, complete, and current information during registration. You are
        responsible for maintaining the confidentiality of your account credentials and for all
        activities that occur under your account. You must notify us immediately of any unauthorized
        use.
      </p>

      <h2>4. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>
          Use the Platform for any unlawful purpose or in violation of any applicable regulations
        </li>
        <li>Attempt to gain unauthorized access to any part of the Platform or its systems</li>
        <li>Interfere with or disrupt the Platform&apos;s infrastructure</li>
        <li>Reverse engineer, decompile, or disassemble any part of the Platform</li>
        <li>Share your account credentials with any third party</li>
      </ul>

      <h2>5. Investment Disclaimer</h2>
      <p>
        <strong>
          The Platform does not provide investment advice. All trading signals, recommendations, and
          analytics are generated by automated systems and are for informational purposes only.
        </strong>{' '}
        You are solely responsible for your own investment decisions. Past performance is not
        indicative of future results. Trading involves substantial risk of loss.
      </p>

      <h2>6. Data and Privacy</h2>
      <p>
        Your use of the Platform is also governed by our{' '}
        <a href="/legal/privacy" className="text-primary hover:underline">
          Privacy Policy
        </a>
        , which describes how we collect, use, and protect your personal information.
      </p>

      <h2>7. Intellectual Property</h2>
      <p>
        All content, features, and functionality of the Platform — including but not limited to
        software, algorithms, text, graphics, and logos — are owned by Sentinel and are protected by
        intellectual property laws.
      </p>

      <h2>8. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, Sentinel shall not be liable for any indirect,
        incidental, special, consequential, or punitive damages, including but not limited to loss
        of profits, data, or trading losses, arising out of your use of the Platform.
      </p>

      <h2>9. Termination</h2>
      <p>
        We reserve the right to suspend or terminate your account at any time for violation of these
        Terms or for any other reason at our sole discretion. Upon termination, your right to use
        the Platform ceases immediately.
      </p>

      <h2>10. Changes to Terms</h2>
      <p>
        We may update these Terms from time to time. We will notify you of material changes by
        updating the version number and effective date at the top of this page. Continued use of the
        Platform after changes constitutes acceptance of the updated Terms.
      </p>

      <h2>11. Contact</h2>
      <p>
        If you have questions about these Terms, please contact us through the Platform&apos;s
        support channels.
      </p>
    </article>
  );
}
