-- ============================================================
-- Migration 00003: Agent tables
-- Trade recommendations + alerts from the AI agent system
-- ============================================================

-- Trade recommendations from AI agents (pending human approval before execution)
CREATE TABLE agent_recommendations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  agent_role text NOT NULL,
  ticker text NOT NULL,
  side text NOT NULL CHECK (side IN ('buy', 'sell')),
  quantity numeric(18,6) NOT NULL,
  order_type text NOT NULL DEFAULT 'market' CHECK (order_type IN ('market', 'limit')),
  limit_price numeric(18,6),
  reason text,
  strategy_name text,
  signal_strength numeric(5,4),
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected', 'filled', 'risk_blocked')),
  order_id text,
  reviewed_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'
);

-- Alerts generated by agents (no user_id — agents run unauthenticated)
CREATE TABLE agent_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  severity text NOT NULL CHECK (severity IN ('info', 'warning', 'critical')),
  title text NOT NULL,
  message text NOT NULL,
  ticker text,
  acknowledged boolean NOT NULL DEFAULT false
);

CREATE INDEX agent_recommendations_status_idx
  ON agent_recommendations(status, created_at DESC);

CREATE INDEX agent_alerts_created_idx
  ON agent_alerts(created_at DESC);
