export const TICKER_NAMES: Record<string, string> = {
  AAPL: 'Apple Inc.',
  MSFT: 'Microsoft Corp.',
  GOOGL: 'Alphabet Inc.',
  AMZN: 'Amazon.com Inc.',
  NVDA: 'NVIDIA Corp.',
  TSLA: 'Tesla Inc.',
  META: 'Meta Platforms',
  JPM: 'JPMorgan Chase',
  V: 'Visa Inc.',
  SPY: 'SPDR S&P 500',
  QQQ: 'Invesco QQQ',
  AMD: 'AMD Inc.',
  NFLX: 'Netflix Inc.',
  DIS: 'Walt Disney',
  BA: 'Boeing Co.',
};

export const SECTOR_MAP: Record<string, string> = {
  AAPL: 'Technology',
  MSFT: 'Technology',
  GOOGL: 'Technology',
  NVDA: 'Technology',
  META: 'Technology',
  AMD: 'Technology',
  NFLX: 'Technology',
  AMZN: 'Consumer',
  TSLA: 'Consumer',
  DIS: 'Consumer',
  JPM: 'Financials',
  V: 'Financials',
  SPY: 'Index',
  QQQ: 'Index',
  BA: 'Industrials',
};

export const SECTOR_COLORS: Record<string, string> = {
  Technology: 'bg-blue-500',
  Financials: 'bg-amber-500',
  Consumer: 'bg-emerald-500',
  Index: 'bg-violet-500',
  Healthcare: 'bg-rose-500',
  Energy: 'bg-orange-500',
  Industrials: 'bg-cyan-500',
};
